### ISSUE TITLE
nimplex install errors

### ISSUE THREAD

**Issue by amr8004** [PhasesResearchLab/AMMap#10]
Issue with the nimplex in AMMap installation. 
Current instructions have added the previously lacking:
nim c --d:release --threads:on --app:lib --out:nimplex.so nimplex/src/nimplex.nim
nim c --d:release --threads:on --app:lib --out:utils/plotting.so nimplex/src/nimplex/utils/plotting.nim

Issue is that current fix I found was to manually move nimplex.so, nimplex.nim, and plotting.nim to respective locations in the AMMap folder. Please help update the install instructions for automated cmd line to install

**Comment by amkrajewski** [comment]
- The above commands use relative paths (like `utils/plotting.so`), so they will depend on where you run them.
- The commands you posted look good in terms of placing executables in the root directory. Is that not the goal?
- We can consider adding a simple `install.sh` script to automate everything for the users.

**Comment by amr8004** [comment]
The way to explain it would be that following the install instructions installs nimplex in a nimplex directory. It does not make the importable nimplex for AMMap to call
Essentially, the step that joins the now built nimplex to the python AMMap so it can run nim commands

**Comment by amr8004** [comment]
In the AMMap folder, with the env active after installing nim run this and it works. Updated README and marking as resolved.

git submodule update --init --recursive && nim c --d:release --threads:on --app:lib --out:nimplex.so nimplex/src/nimplex.nim && nim c --d:release --threads:on --app:lib --out:utils/plotting.so nimplex/src/nimplex/utils/plotting.nim
