### ISSUE TITLE
(Fix inclded) 3D Equilibirum Feasibility Figure: "Equilibrium Phase Present" label gives incorrect response

### ISSUE THREAD

**Issue by NickOldham** [PhasesResearchLab/AMMap#9]
In AMMapDemonstration, code block 31, we have;

fig = px.scatter_3d(gridAtt_projected_df, x='x', y='y', z='z', color=gridFeasible, text=labels, hover_name=formulas,
              template='plotly_white', width=800, height=700, opacity=0.333, color_discrete_sequence=['green', 'red'],
              labels={'color':'Infeasible Phase Present', 'x':'', 'y':'', 'z':''}, title='Equilibrium Calculation')
fig.update_scenes({'camera': {'eye': {'x': -2.3, 'y': 0.2, 'z': 0.2}}})

The generated figure displays red and green sections of a tetrahedral feasibility diagrams, with infeasible regions being determined by the presence of unwanted phases above a certain concentration.

When the user hovers over a given node, they view the a label that states the node composition and node feasibility. THe node feasibility is described using one of two lines, either;

Infeasible Phase Present = True
or
Infeasible Phase Present = False

In the current active branch, nodes in the red, infeasible region return "False" while notes in the green, feasible region return "True." This is incorrect. A simple fix to this problem is to change the text in the label to instead state "No Infeasible Phase Present" or "Feasible Composition" instead of "Infeasible Phase Present".

**Comment by amr8004** [comment]
Should be cleared up in new commit to main. Will not automatically update in your Codespace
